/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package csg;

/**
 *
 * @author dsli
 */
public enum CSGProp {
    //Tab Labels
    COURSE_DETAILS_TAB,
    TA_DATA_TAB,
    RECITATION_DATA_TAB,
    SCHEDULE_DATA_TAB,
    PROJECT_DATA_TAB,
    
    //UNIVERSAL CSG BUTTON LABELS
    CHANGE_BUTTON_LABEL,
    ADD_BUTTON_LABEL,
    ADD_UPDATE_BUTTON_LABEL,
    DELETE_SYMBOL,
    ADD_EDIT_LABEL,
    CLEAR_BUTTON_LABEL,
    
    //COURSE DETAILS TAB LABELS
    COURSE_SUBJECT_LABEL,
    COURSE_INFO_LABEL,
    COURSE_NUMBER_LABEL,
    COURSE_SEMESTER_LABEL,
    COURSE_TITLE_LABEL,
    COURSE_INSTRUCTOR_NAME_LABEL,
    COURSE_INSTRUCTOR_HOME_LABEL,
    COURSE_EXPORT_DIR_LABEL,
    COURSE_SITE_TEMPLATE_LABEL,
    COURSE_SITE_TEMPLATE_NOTE_LABEL,
    COURSE_SELECT_TEMPLATE_DIRECTORY_BUTTON_LABEL,
    COURSE_SITE_PAGES_LABEL,
    COURSE_SITE_PAGES_USE_LABEL,
    COURSE_SITE_PAGES_NAVBAR_TITLE_LABEL,
    COURSE_SITE_PAGES_FILE_NAME_LABEL,
    COURSE_SITE_PAGES_SCRIPT_LABEL,
    COURSE_HOME_PAGE_LABEL,
    COURSE_SYLLABUS_PAGE_LABEL,
    COURSE_SCHEDULE_PAGE_LABEL,
    COURSE_HW_PAGE_LABEL,
    COURSE_PROJECTS_PAGE_LABEL,
    COURSE_PAGE_STYLE_LABEL,
    COURSE_BANNER_SCHOOL_IMAGE_LABEL,
    COURSE_LEFT_FOOTER_LABEL,
    COURSE_RIGHT_FOOTER_LABEL,
    COURSE_STYLESHEET_LABEL,
    COURSE_STYLESHEET_NOTE_LABEL,
    
    //TA DATA TAB LABELS
    TEACHING_ASSISTANTS_LABEL,
    TA_UNDERGRAD_LABEL,
    TA_NAME_LABEL,
    TA_EMAIL_LABEL,
    OFFICE_HOURS_LABEL,
    OFFICE_HOURS_START_LABEL,
    OFFICE_HOURS_END_LABEL,
    
    //RECITATION DATA TAB LABELS
    REC_SECTION_LABEL,
    REC_INSTRUCTOR_LABEL,
    REC_DAY_TIME_LABEL,
    REC_LOCATION_LABEL,
    REC_TA1_LABEL,
    REC_TA2_LABEL,
    
    //SCHEDULE DATA TAB LABELS
    CALENDAR_BOUNDARIES_LABEL,
    STARTING_MONDAY_LABEL,
    ENDING_FRIDAY_LABEL,
    SCHEDULE_ITEMS_LABEL,
    SCHEDULE_ITEM_TYPE_LABEL,
    SCHEDULE_ITEM_DATE_LABEL,
    SCHEDULE_ITEM_TITLE_LABEL,
    SCHEDULE_ITEM_TOPIC_LABEL,
    SCHEDULE_ITEM_TIME_LABEL,
    SCHEDULE_ITEM_LINK_LABEL,
    SCHEDULE_ITEM_CRITERIA_LABEL,
    
    //WORKSPACE CONTROLS STUFF
    TAS_HEADER_TEXT,
    NAME_COLUMN_TEXT,
    EMAIL_COLUMN_TEXT,
    NAME_PROMPT_TEXT,
    EMAIL_PROMPT_TEXT,
    ADD_BUTTON_TEXT,
    
    //PROJECT DATA TAB LABELS
    TEAMS_LABEL,
    TEAM_NAME_LABEL,
    TEAM_COLOR_LABEL,
    TEXT_COLOR_LABEL,
    TEAM_LINK_LABEL,
    TEAM_STUDENTS_LABEL,
    STUDENT_FIRST_NAME_LABEL,
    STUDENT_LAST_NAME_LABEL,
    STUDENT_TEAM_LABEL,
    STUDENT_ROLE_LABEL,
    
    //WORKSPACE ERROR MESSAGES
    OFFICE_HOURS_TABLE_HEADERS,
    DAYS_OF_WEEK,
}
