/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package csg;

/**
 *
 * @author dsli
 */
public enum CSGProp {
    //Tab Labels
    COURSE_DETAILS_TAB,
    TA_DATA_TAB,
    RECITATION_DATA_TAB,
    SCHEDULE_DATA_TAB,
    PROJECT_DATA_TAB,
    
    //PATH NAMES FOR DEFAULT IMAGES IN THE COURSE DETAILS TAB
    DEFAULT_BANNER_SCHOOL_IMAGE,
    DEFAULT_LEFT_FOOTER_IMAGE,
    DEFAULT_RIGHT_FOOTER_IMAGE,
    
    //UNIVERSAL CSG BUTTON LABELS
    CHANGE_BUTTON_LABEL,
    ADD_BUTTON_LABEL,
    EDIT_BUTTON_LABEL,
    ADD_UPDATE_BUTTON_LABEL,
    DELETE_SYMBOL,
    ADD_EDIT_LABEL,
    CLEAR_BUTTON_LABEL,
    
    //COURSE DETAILS TAB LABELS
    COURSE_SUBJECT_LABEL,
    COURSE_INFO_LABEL,
    COURSE_NUMBER_LABEL,
    COURSE_SEMESTER_LABEL,
    COURSE_YEAR_LABEL,
    COURSE_TITLE_LABEL,
    COURSE_INSTRUCTOR_NAME_LABEL,
    COURSE_INSTRUCTOR_HOME_LABEL,
    COURSE_EXPORT_DIR_LABEL,
    COURSE_SITE_TEMPLATE_LABEL,
    COURSE_SITE_TEMPLATE_NOTE_LABEL,
    COURSE_SELECT_TEMPLATE_DIRECTORY_BUTTON_LABEL,
    COURSE_SITE_PAGES_LABEL,
    COURSE_SITE_PAGES_USE_LABEL,
    COURSE_SITE_PAGES_NAVBAR_TITLE_LABEL,
    COURSE_SITE_PAGES_FILE_NAME_LABEL,
    COURSE_SITE_PAGES_SCRIPT_LABEL,
    COURSE_HOME_PAGE_LABEL,
    COURSE_SYLLABUS_PAGE_LABEL,
    COURSE_SCHEDULE_PAGE_LABEL,
    COURSE_HW_PAGE_LABEL,
    COURSE_PROJECTS_PAGE_LABEL,
    COURSE_PAGE_STYLE_LABEL,
    COURSE_BANNER_SCHOOL_IMAGE_LABEL,
    COURSE_LEFT_FOOTER_LABEL,
    COURSE_RIGHT_FOOTER_LABEL,
    COURSE_STYLESHEET_LABEL,
    COURSE_STYLESHEET_NOTE_LABEL,
    
    // STYLESHEET SELECT COMBO BOX VALUES
    CSG_SEA_WOLF_CSS,
    COURSE_HOMEPAGE_LAYOUT,
    
    // COMBO BOX LABELS FOR COURSE DETAILS TAB
    CSE_LABEL,
    ISE_LABEL,
    FALL_SEMESTER,
    SPRING_SEMESTER,
    
    // COMBO BOX LABELS FOR SCHEDULE ITEMS TAB
    LECTURE_EVENT,
    HOLIDAY_EVENT,
    REFERENCE_EVENT,
    HOMEWORK_EVENT,
    RECITATION_EVENT,
    
    //TA DATA TAB LABELS
    TEACHING_ASSISTANTS_LABEL,
    TA_UNDERGRAD_LABEL,
    TA_NAME_LABEL,
    TA_EMAIL_LABEL,
    OFFICE_HOURS_LABEL,
    OFFICE_HOURS_START_LABEL,
    OFFICE_HOURS_END_LABEL,
    
    //RECITATION DATA TAB LABELS
    RECITATIONS_LABEL,
    REC_SECTION_LABEL,
    REC_INSTRUCTOR_LABEL,
    REC_DAY_TIME_LABEL,
    REC_LOCATION_LABEL,
    REC_TA1_LABEL,
    REC_TA2_LABEL,
    
    //SCHEDULE DATA TAB LABELS
    CALENDAR_BOUNDARIES_LABEL,
    STARTING_MONDAY_LABEL,
    ENDING_FRIDAY_LABEL,
    SCHEDULE_ITEMS_LABEL,
    SCHEDULE_ITEM_TYPE_LABEL,
    SCHEDULE_ITEM_DATE_LABEL,
    SCHEDULE_ITEM_TITLE_LABEL,
    SCHEDULE_ITEM_TOPIC_LABEL,
    SCHEDULE_ITEM_TIME_LABEL,
    SCHEDULE_ITEM_LINK_LABEL,
    SCHEDULE_ITEM_CRITERIA_LABEL,
    
    //WORKSPACE CONTROLS STUFF
    TAS_HEADER_TEXT,
    NAME_COLUMN_TEXT,
    EMAIL_COLUMN_TEXT,
    IS_UNDERGRAD_COLUMN_TEXT,
    NAME_PROMPT_TEXT,
    EMAIL_PROMPT_TEXT,
    HOME_PROMPT_TEXT,
    ADD_BUTTON_TEXT,
    
    //PROJECT DATA TAB LABELS
    TEAMS_LABEL,
    TEAM_NAME_LABEL,
    TEAM_COLOR_LABEL,
    TEXT_COLOR_LABEL,
    TEAM_LINK_LABEL,
    TEAM_STUDENTS_LABEL,
    STUDENT_FIRST_NAME_LABEL,
    STUDENT_LAST_NAME_LABEL,
    STUDENT_TEAM_LABEL,
    STUDENT_ROLE_LABEL,
    
    //ERROR MESSAGES - RECITATION TAB
    MISSING_RECITATION_SECTION_TITLE,
    MISSING_RECITATION_SECTION_MESSAGE,
    MISSING_RECITATION_INSTRUCTOR_TITLE,
    MISSING_RECITATION_INSTRUCTOR_MESSAGE,
    MISSING_RECITATION_DAY_TIME_TITLE,
    MISSING_RECITATION_DAY_TIME_MESSAGE,
    MISSING_RECITATION_LOCATION_TITLE,
    MISSING_RECITATION_LOCATION_MESSAGE,
    MISSING_RECITATION_TA_TITLE,
    MISSING_RECITATION_TA_MESSAGE,
    SAME_TA_TITLE,
    SAME_TA_MESSAGE,
    
    //WORKSPACE ERROR MESSAGES
    OFFICE_HOURS_TABLE_HEADERS,
    DAYS_OF_WEEK,
    
    // ERROR MESSAGES - SCHEDULE TAB
    BAD_START_END_DATES_TITLE,
    BAD_START_END_DATES_MESSAGE,
    
    // THESE ARE FOR ERROR MESSAGES PARTICULAR TO THE APP - TADATA TAB
    MISSING_TA_NAME_TITLE,
    MISSING_TA_NAME_MESSAGE,
    MISSING_TA_EMAIL_TITLE,
    MISSING_TA_EMAIL_MESSAGE,
    TA_NAME_AND_EMAIL_NOT_UNIQUE_TITLE,
    TA_NAME_AND_EMAIL_NOT_UNIQUE_MESSAGE,
    TA_EMAIL_INVALID_TITLE,
    TA_EMAIL_INVALID_MESSAGE,
    OFFICE_HOURS_REMOVED_TITLE,
    OFFICE_HOURS_REMOVED_MESSAGE,
    START_OVER_END_TITLE,
    START_OVER_END_MESSAGE,
    
    TIME_12AM,
    TIME_1AM,
    TIME_2AM,
    TIME_3AM,
    TIME_4AM,
    TIME_5AM,
    TIME_6AM,
    TIME_7AM,
    TIME_8AM,
    TIME_9AM,
    TIME_10AM,
    TIME_11AM,
    TIME_12PM,
    TIME_1PM,
    TIME_2PM,
    TIME_3PM,
    TIME_4PM,
    TIME_5PM,
    TIME_6PM,
    TIME_7PM,
    TIME_8PM,
    TIME_9PM,
    TIME_10PM,
    TIME_11PM
}
